### ISSUE TITLE
Make soa-model available via Maven Central

### ISSUE THREAD

**Issue by b0n541** [membrane/soa-model#221]
For better distribution it would be nice to have soa-model available on Maven Central. A lot of companies have mirrors of Maven Central behind their proxies for making external libraries available to the developers.

**Comment by PascalSchumacher** [comment]
I just noticed that 1.5 has been published to maven central:

http://search.maven.org/#artifactdetails|com.predic8|soa-model-core|1.5.0|jar

Thank you very much!

This means this issue can be closed.

**Comment by predic8** [comment]
Thx @PascalSchumacher @b0n541
