### ISSUE TITLE
Compare non-backward compatible Differences

### ISSUE THREAD

**Issue by davidkuehner** [membrane/soa-model#251]
**Feature:**
Get the list of non-backward compatible Differences between two wsdl files.

Same as WsdlDiffGenerator:compare without the following backward compatible Differences :
 
- adding a new optional request elements (minoccurs=0)
- adding a new WSDL operation definition and associated message definitions
- adding a new WSDL port type definition and associated operation definitions
- adding new WSDL binding and service definitions
- adding a new optional XML Schema element or attribute declaration to a message definition
- reducing the constraint granularity of an XML Schema element or attribute of a message definition type
- adding a new XML Schema wildcard to a message definition type
- adding a new optional WS-Policy assertion
- adding a new WS-Policy alternative

```
Definitions wsdl1 = parser.parse("resources/diff/1/article.wsdl");
Definitions wsdl2 = parser.parse("resources/diff/2/article.wsdl");
WsdlBackwardCompatibilityGenerator backCompatGen = new WsdlBackwardCompatibilityGenerator(wsdl1, wsdl2);
List<Difference> lst = backCompatGen.compare();
```

Links: 

- http://stackoverflow.com/questions/8786935/what-are-considered-non-breaking-or-backwards-compatible-changes-to-a-wsdl-contr
- http://www.ibm.com/developerworks/webservices/library/ws-version/#1

**Comment by predic8** [comment]
Thanks for the list. We build our own understanding of backward compatibility into SOA model e.g. adding an optional Schema element often breaks the interface. If a party is receiving the new element that does not understand it, it will raise an error. Unfortunately there only few tools that ignore optional elements. So you have to consider the direction. We build that into our tool. Have a look at:

https://www.wsdl-analyzer.com/diff/show/2023352896?version=1&modifiedVersion=2

to see it in action. You can reverse the direction of the compare and see that you get different results. Much better would be, if you can specify what tools you are using and the lib considers this. But this are Web Services that are made for interoperability. So if there are some tools that break then the interface breaks.

**Comment by davidkuehner** [comment]
Ok thanks for the info.
Is the Difference.breaks() your backward compatibility flag?

**Comment by predic8** [comment]
yes

**Comment by davidkuehner** [comment]
Nice.
And what mean null ? Cannot be defined?

**Comment by predic8** [comment]
I think so in the meaning of null. You can not tell. But I have not look in the code for a long time.
