### ISSUE TITLE
Release version 1.6.1

### ISSUE THREAD

**Issue by tpunder** [membrane/soa-model#264]
Can we get a 1.6.1 release?

I'm specifically interested in picking up https://github.com/membrane/soa-model/commit/0705e1c693cd79450fd6b6a31d4e97f6e350aeb2 without relying on a locally published version.

**Comment by er1c** [comment]
@predic8 @rrayst any chance we can get this released?  It's been over a year now and we still have to publish local instead of using a normal maven dependency :)

**Comment by er1c** [comment]
@predic8 @rrayst bumping this, please? :)

**Comment by er1c** [comment]
@predic8 @rrayst bump?

**Comment by er1c** [comment]
@predic8 @rrayst @xorpherion bump?

**Comment by rrayst** [comment]
thanks for the ping, sorry for the delay!
