### ISSUE TITLE
Displaying similarity percentage of comparing XSD

### ISSUE THREAD

**Issue by balnamlah** [membrane/soa-model#275]
Is there a way to display the similarity percentage of comparing XSD files?
Currently the code displays the difference as a text, I need it as a number

**Comment by rrayst** [comment]
Hi @balnamlah , soa-model currently offers no such functionality. Feel free to
* use the library and count the length of the diff, comparing it to the number of lines in the schemas
* create a pull request adding statistics.

**Comment by balnamlah** [comment]
how to count the length of the diff? is there a method?

**Comment by balnamlah** [comment]
here is the code 
```
 List<Difference> lst = diffGen.compare();
	    for (Difference diff : lst) {
	    	 
	      dumpDiff(diff, "");	
	     
	    }
System.out.println("counter is" +counter);
	}
	   
	 
	   
	  private static void dumpDiff(Difference diff, String level) {
		 
		  
	    System.out.println( level + diff.getDescription());
	  

	    for (Difference localDiff : diff.getDiffs()){
	      dumpDiff(localDiff, level + "  ");
	      counter++;
	     
	    }
```

the counter will count each time system enter this method which is wrong 
If this is my output 
```
ComplexType Address removed.
ComplexType Student:
  Sequence:
    Element course:
      MinOccurs changed from 0 to 1.
  Attribute grade removed.
ComplexType Course:
  The attribute use has changed from optional to required.
```

the result is = 5, but it should be = 4
